version: '3'
services:
  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scfg
    networks:
      - scfgnet

  scfg:
    build:
      context: ./docker/scfg
    container_name: scfg
    volumes:
      - .:/go/src/github.com/vlamug/scfg
    ports:
      - "9002:9002"
    networks:
      - scfgnet
    links:
      - database
    command: make run

  #migration:
  #  build:
  #    context: ./docker/migration
  #  container_name: migration
  #  volumes:
  #    - ./migrations:/migrations
  #  links:
  #    - database

networks:
  scfgnet: